version: "3.3"
services:
    app:
        build: .
        restart: unless-stopped
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/app
        ports:
            - 127.0.0.1:8090:80
        networks:
            - twenty-tech
        env_file:
            - ./.env
networks:
    twenty-tech:
        driver: bridge
